services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
  main_app:
    image: main_app
    container_name: main_app
    ports:
      - 8080:8080
    links:
      - mongodb